### PR TITLE
[RHIDP-436] Add PR commenter bot to add links to test logs as PR comment

### PR DESCRIPTION
**Pull request by josephca**
Fixes [[Test automation] Integrate PRs with CI infra to add links within PRs to test logs](https://issues.redhat.com/browse/RHIDP-436)

### CODE REVIEW

**Comment by josephca** [comment]
@subhashkhileri Please review. Now it displays [the test log](https://s3.eu-de.cloud-object-storage.appdomain.cloud/backstage-pr-tests-bucket/pr-51-openshift-tests-293.html) fine.  Also, it's using https://www.npmjs.com/package/cypress-terminal-report to generate more detailed test log.

**Comment by subhashkhileri** [comment]
> @subhashkhileri Please review. Now it displays [the test log](https://github.com/janus-idp/showcase-e2e/pull/51#issuecomment-1783577014) fine. Also, it's using https://www.npmjs.com/package/cypress-terminal-report to generate more detailed test log.

@josephca, the logs look pretty good now—thank you. I've noticed that the same comment is being edited/updated by the bot even for new test runs. Creating a new comment for each run will retain the old log, allowing us to cross-check the latest and old logs. What do you think?

**Comment by josephca** [comment]
> @subhashkhileri Please review. Now it displays [the test log](https://github.com/janus-idp/showcase-e2e/pull/51#issuecomment-1783577014) fine. Also, it's using https://www.npmjs.com/package/cypress-terminal-report to generate more detailed test log.

I've noticed the behavior as well. I think that's how pr-commenter is implemented. I'll take another look.

**Comment by josephca** [comment]
Now the test result shows as [**bold** font](https://github.com/janus-idp/showcase-e2e/pull/51#issuecomment-1783577014).

**Pull request merged**
