### PR TITLE
Refactor for openshift-tests.sh

### PR DESCRIPTION
**Pull request by gustavolira**
**Reduced Code Duplication** for Helm repositories.

**Conditional Installation**: Added `install_tool` function to check if  functions like `install_helm`, `install_ibmcloud`, and `install_oc` are already installed. This avoids unnecessary installations and saves time.

**Use of Variables for Paths:** The script now uses variables to store paths and directories

### CODE REVIEW

**Comment by josephca** [comment]
@gustavolira It looks great. Minor caveat - could you fix some off indentations? also, we may enhance it further in the future to install tools within [the base image](https://github.com/janus-idp/showcase-e2e/blob/main/.ibm/images/Dockerfile) used for tests.

**Comment by gustavolira** [comment]
> @gustavolira It looks great. Minor caveat - could you fix some off indentations? also, we may enhance it further in the future to install tools within [the base image](https://github.com/janus-idp/showcase-e2e/blob/main/.ibm/images/Dockerfile) used for tests.

@josephca code formatted.

**Review by josephca — APPROVED** [review]
LGTM

**Comment by josephca** [comment]
@gustavolira please sign when you commit. Thanks!

**Pull request merged**
